apiVersion: v1
kind: Service
metadata:
  name: devops
  labels:
    app: devops
spec:
  type: LoadBalancer
  ports:
  - port: 3000
  selector:
    app: devops
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops
  labels:
    app: devops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops
  template:
    metadata:
      labels:
        app: devops
    spec:
      containers:
      - name: devops
        image: sarahkaddour/devopsimage:latest
        ports:
        - containerPort: 3000