version: '3'
services:
    backend:
        container_name: backend
        build: ./devops_backend
        ports:
            - '8000:8000'
    frontend:
        container_name: frontend
        build: ./devops_frontend
        ports:
            - '3000:3000'
        links:
            - backend